### PR TITLE
Cleaned up the repostiory and updated README.md

### PR DESCRIPTION
**Pull request by PureTryOut**
Cleaned up the repository.

- Removed not needed, not used scripts and renamed build_elf.sh to a more clearer name
- Moved license to it's own file
- Removed changelog.txt, this should not be kept in a repository
- Updated .gitignore to include the C/C++ presets of Github, and also ignore stock Cod4 server files
- Added build instructions for Linux to README.md (I don't use Windows for this kind of stuff so I can't really add Windows instructions)
- Added a short description of what Cod4X is in README.md

TODO: Create proper Wiki pages with more detailed information on how to setup a Cod4X server, such as explanation of config files and it's variables.

### CODE REVIEW

**Comment by PureTryOut** [comment]
For info: the build fails since it tries to chmod build_updateable_elf.sh. However, I renamed the script to build_linux.sh to make it more clear what exactly it builds. Change Travis to build from this script instead.

Also chmod is not required anymore, since the files are already executable in this PR.

**Comment by D4edalus** [comment]
Thanks for the contribution :) 
Because our active development still happens in a different repository I won't integrate your code changes here yet, but will take over some parts of it to our private repo.

Documentation is very welcome! If you are motivated to implement things yourself let us know. I'll also prepare some todos in the issue tracker.

**Comment by PureTryOut** [comment]
Aah I did not know that, Ninja/Fraggy just linked me this one ;)

I'm not much of a coder yet although I do know some Lua (hint hint, maybe as alternative to C++ based plugins?). I can however help with documentation, I'm planning on writing a proper guide to setup Cod4X servers with explanation of the config file variables etc. Best place for that is probably the Github Wiki.

**Comment by PureTryOut** [comment]
Also note, xiceops_00.iwd in bin/main should not be distributed in this repository. It's against the license.

(A)GPL allows programs to depend on proprietary software, it just may not be shipped together. Of course it would be preferable to not depend on proprietary software (in this case the original server binary) at all but that is a whole other beast.
Giving a seperate download link would do.

**Comment by D4edalus** [comment]
having a more detailed guide in the wiki would be awesome!
i've also copy pasted some of the new variables to a github page that are very well hidden in code, but can be interesting for hosters

thx for pointing out the licensing problem. that's a little tedious, but i guess we can host that on another link.. maybe just on a second github repository? .. that would even allow to pull it in as a git submodule easily

**Comment by PureTryOut** [comment]
I guess so, just as long as it's not distributed with Cod4X itself. Same goes with that proprietary module Ninja talked about, for including Steam support, screenshots, and other anti-features. It should be distributed seperately.

**Comment by dschoerk** [comment]
do you know if you can make a pull-request for wikipages ?

**Comment by D4edalus** [comment]
do you know if its possible to make pull-requests for wiki pages?

**Comment by PureTryOut** [comment]
I don't think so. I'm just making it in my own fork now and I'll just give you a link to the source.

**Comment by D4edalus** [comment]
aight

**Comment by PureTryOut** [comment]
[I've created an initial version](https://github.com/PureTryOut/CoD4x1.8_Server_Pub/wiki/Setup-tutorial). I added some TODO's in **bold** as I was either not certain how to do it, or the wiki have to be expanded first for any links.

Also if you want, there exists an IRC channel for Cod4X. It's created a while ago, and it's on irc.rizon.net. Join the channel #cod4x.

I have not been on the forums for a while before yesterday, but I see the same amount of mess as before. Could you guys use a moderator to clean some things up? Things like archiving old (done) posts, placing code and errors between [code][/code] tags wherever possible (if the other users don't do it themselves), etc. I'm volunteering ;)

**Comment by PureTryOut** [comment]
[Added an default config file](https://github.com/PureTryOut/CoD4x1.8_Server_Pub/wiki/Example-configuration) people can use as example. I have as much cvar's explained as I could, but I'm missing some explanations.

Do I miss some variables here?

**Comment by PureTryOut** [comment]
I just noticed I missed the `+exec server.cfg` in the required startup parameters in the setup guide.

You could add the following just underneath the "Configuration" header:

```
+exec server.cfg
```
* `+exec server.cfg` Executes your config file

**Pull request closed without merging**
